
LTC2943-battery-monitor: LTC2943-battery-monitor.c LTC2943/LTC2943.c
	gcc LTC2943-battery-monitor.c LTC2943/LTC2943.c -lwiringPi -I ./LTC2943 -o LTC2943-battery-monitor

clean:
	rm LTC2943-battery-monitor

